Практика №9. Разработка с помощью PyQt5
WutenderBorsch/Collective-IT-activities pull request #13
Opened 2021-05-29 11:03 UTC by WutenderBorsch

Вариант 2.

1. Написать приложение, выполняющее построение синусоиды. Период синусоиды должен задаваться с помощью слайдера (QSlider).
2. Написать приложение, выполняющее просмотр изображений из указанного каталога. Должна быть возможность переходить от изображения к изображению с помощью кнопок «Влево» и «Вправо».

2021-06-02 16:46 UTC, silentonni commented
Всё хорошо всё отлично!

2021-06-02 16:48 UTC, silentonni commented on 1. Построение синусоиды/main.py
> +class Window(QDialog):
Всё хорошо всё отлично!

2021-06-07 14:13 UTC, silentonni commented on 2. Просмотр изображений/main.py
> +    return
Можно объединить в одну строку: return lable.setPixmap(pixmap).

2021-06-07 14:13 UTC, silentonni commented on 2. Просмотр изображений/main.py
> +    return
Можно объединить в одну строку: return lable.setPixmap(pixmap).

2021-06-07 16:11 UTC, stanislavlyalin requested changes

2021-06-07 16:11 UTC, stanislavlyalin commented on 1. Построение синусоиды/main.py
> +    def foo(self, value):
Метод не используется. Удалить

2021-06-07 16:11 UTC, stanislavlyalin commented on 1. Построение синусоиды/main.py
> +        uic.loadUi('untitled.ui', self)
`untitled.ui` - название не удачное. Дать осмысленное имя файлу

2021-06-07 16:11 UTC, stanislavlyalin commented on 1. Построение синусоиды/main.py
> +sys.exit(app.exec_())
Лучше обернуть так:
```python
if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Window()
    ex.show()
    sys.exit(app.exec_())

2021-06-07 16:11 UTC, stanislavlyalin commented on 2. Просмотр изображений/main.py
> +w = QWidget()
Этот код тоже лучше обернуть, как я показал выше

2021-06-07 16:11 UTC, stanislavlyalin commented on 2. Просмотр изображений/main.py
> +    quit()
Сделать отдельный класс для окна приложения. Открытие каталога, поиск файлов, построение списка изображений делать в конструкторе класса

2021-06-07 16:11 UTC, stanislavlyalin commented on 2. Просмотр изображений/main.py
> +lable = QLabel(w)
Наверное, всё-таки, `label`? :)

2021-06-07 16:11 UTC, stanislavlyalin commented on 2. Просмотр изображений/main.py
> +lable.setMaximumHeight(500)
Это тоже можно перенести в конструктор класса

2021-06-07 16:11 UTC, stanislavlyalin commented on 2. Просмотр изображений/main.py
> +    return lable.setPixmap(pixmap)
Методы `left` и `right` должны быть в том же классе окна, о котором я написал выше

2021-06-07 16:11 UTC, stanislavlyalin commented on 2. Просмотр изображений/main.py
> +    fight.clicked.connect(lambda: Right(x))
Связывание кнопок и действий должно быть в конструкторе класса

2021-06-08 02:46 UTC, merged