Практика №2. Введение в программирование на Python
WutenderBorsch/Collective-IT-activities pull request #14
Opened 2021-05-31 16:03 UTC by Veronika2125

2021-06-02 14:59 UTC, WutenderBorsch requested changes

2021-06-02 14:59 UTC, WutenderBorsch commented on Task3.py
> +
Циклический сдвиг элементов массива надо было реализовать как функцию

2021-06-02 14:59 UTC, WutenderBorsch commented on Task5.py
> +
Вычисление евклидова расстояния нужно было реализовать как функцию

2021-06-04 17:40 UTC, WutenderBorsch commented on Task3.py
> +    return b
Можно объединить в одну строку

2021-06-04 17:40 UTC, WutenderBorsch commented on Task5.py
> +    return evRast
Можно объединить в одну строку

2021-06-07 15:35 UTC, stanislavlyalin requested changes

2021-06-07 15:35 UTC, stanislavlyalin commented on Task6.py
> +    if a == b:
Переменных `a` и `b` нет в этой функции. Размеры матрицы можно получить с помощью свойства `shape`:
```python
m, n = x.shape  # m - число строк, n - число столбцов
```

2021-06-08 02:45 UTC, merged