Практика №2. Алгоритм классификации k ближайших соседей
WutenderBorsch/Collective-IT-activities pull request #16
Opened 2021-06-02 15:26 UTC by Veronika2125

2021-06-02 15:56 UTC, WutenderBorsch commented on kNN.py
> +    distance = np.zeros((16, k-1))
Число 16 можно заменить на len(X), как и в строчке ниже

2021-06-02 15:56 UTC, WutenderBorsch commented on kNN.py
> +
Нормализацию можно записать немного короче (не используя переменную):
mx=np.max(X[:, 0:-1], axis=0)
norm_X = X[:, 0:-1]/mx

2021-06-03 17:24 UTC, stanislavlyalin requested changes

2021-06-03 17:24 UTC, stanislavlyalin commented on kNN.py
> +    norm_obj = obj/mx
Нужно реализовать стандартизацию, т.е. вычитание среднего и деление на среднеквадратическое отклонение

2021-06-03 17:24 UTC, stanislavlyalin commented on kNN.py
> +       distance[i] = dist(norm_X[i], norm_obj)
Можно объединить в 1 строку, используя генераторы списков

2021-06-03 17:24 UTC, stanislavlyalin commented on kNN.py
> +    for i in range(4):
Откуда волшебная константа `4`? Алгоритм должен быть универсальным и работать с любыми данными, а не только с обезьянками, поэтому брать надо значение числа соседей `k`, переданное как параметр

2021-06-03 17:24 UTC, stanislavlyalin commented on run.py
> +weight = int(input("Введите вес: "))
Если ввести не числа, а, например, буквы, преобразование в `int` не сработает, поэтому код лучше обернуть в `try-except`, чтобы исключить ошибки преобразования строки в целое число

2021-06-07 15:28 UTC, merged