practice №3
WutenderBorsch/Collective-IT-activities pull request #5
Opened 2021-04-20 10:52 UTC by Veronika2125

2021-04-27 16:07 UTC, silentonni commented on pract-03/k_means.py
> +  centers = np.random.random((k, n))
Не найдены границы минимальных и максимальных значений столбцов (признаков) матрицы X

2021-06-03 17:19 UTC, stanislavlyalin requested changes

2021-06-03 17:19 UTC, stanislavlyalin commented on pract-03/k_means.py
> +def dist(A, B):
Лучше переименовать в `euclidean_distance`

2021-06-03 17:19 UTC, stanislavlyalin commented on pract-03/k_means.py
> +  r=math.sqrt(sum((A-B)**2))
Необходимо проверять, что `A` и `B` являются переменными типа `np.ndarray`

2021-06-03 17:19 UTC, stanislavlyalin commented on pract-03/k_means.py
> +  return r
Можно объединить в одну строку

2021-06-03 17:19 UTC, stanislavlyalin commented on pract-03/k_means.py
> +        distances[i, j] = dist(centers[j], X[i])
Используя генераторы списков, объедините строки в одну. Примерный код:
```python
distances = [[<ваш код> for j in range(k)] for i in range(m)]
```

2021-06-03 17:19 UTC, stanislavlyalin commented on pract-03/k_means.py
> +  n = X.shape[1]
Можно так:
```python
m, n = X.shape
```

2021-06-03 17:19 UTC, stanislavlyalin commented on pract-03/k_means.py
> +  # TODO: инициализировать переменные m и n
Комментарии `TODO` лучше убрать, или хотя бы убрать слово `TODO`

2021-06-07 15:24 UTC, merged