Практика №5.  Дерево решений
WutenderBorsch/Collective-IT-activities pull request #8
Opened 2021-04-27 16:12 UTC by WutenderBorsch

Реализация классификатора на основе дерева решений. 
В заключении можно попробовать проверить себя на роль ассистентки профессора Буковски <(￣︶￣)>

2021-06-02 16:35 UTC, Veronika2125 commented on pract-05/decision_tree.py
> +    # TODO: реализуйте проверку того, что текущий узел необходимо объявить листом
Все комментарии TODO можно убрать

2021-06-03 17:29 UTC, stanislavlyalin requested changes

2021-06-03 17:29 UTC, stanislavlyalin commented on pract-05/decision_tree.py
> +    m = X.shape[0]  # количество примеров
Можно объединить в одну строку:
```python
m, n = X.shape
```

2021-06-03 17:29 UTC, stanislavlyalin commented on pract-05/decision_tree.py
> +             temp = len(Tj) / len(X[:, i])
`temp` название не очень удачное. Лучше, например, `weight`, т.к. по сути это весовой коэффициент

2021-06-03 17:29 UTC, stanislavlyalin commented on pract-05/decision_tree.py
> +        info += p * np.log2(p)
Можно так:
```python
info += p * np.log2(p) if p > 0 else 0
```

2021-06-03 17:29 UTC, stanislavlyalin commented on pract-05/decision_tree.py
> +    return info
```python
return -info
```

2021-06-07 15:31 UTC, stanislavlyalin requested changes

2021-06-07 15:31 UTC, stanislavlyalin commented on pract-05/decision_tree.py
> +        info += p * np.log2(p) if p > 0 else 0
Если используется выражение `info += p * np.log2(p) if p > 0 else 0`, то в проверке
```python
if p == 0:
    continue
```
нет необходимости

2021-06-07 15:31 UTC, stanislavlyalin commented on pract-05/decision_tree.py
> +    return -info
Минус на минус даёт плюс, т.е. `info`, фактически, остаётся с исходным знаком. 113 строка не нужна

2021-06-07 15:58 UTC, merged